name: sgtp_flutter
description: SGTP secure group chat client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  shared_preferences: ^2.3.3
  file_picker: ^10.3.10
  cryptography: ^2.7.0
  path_provider: ^2.1.4
  record: ^6.2.0
  audioplayers: ^6.1.0
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  pasteboard: ^0.2.0
  pretty_qr_code: ^3.5.0
  image: ^4.5.4
  image_picker: ^1.1.2
  window_manager: ^0.4.3
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.2.3
  camera: ^0.11.0
  flutter_zxing: ^2.2.1
  camera_desktop: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - web/icons/Icon-192.png
